//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspIdentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int Id { get; set; }
        public Nullable<int> Projects_Id { get; set; }
        public string ApplicationUser_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
