//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspIdentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime FinishTime { get; set; }
        public System.DateTime PredictedFinishTime { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual States States { get; set; }
    }
}
